<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="EXPIRES" content="-1">

<title>WebTricks CMS</title>

<!-- TINY MCE HTML EDITOR -->
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>

<!-- EXT JS LIBRARY -->
<link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all.css" />
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base-debug.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>

<!--  EXT JS EXTENSIONS -->
<script type="text/javascript" src="/js/extjs/ux/ribbon.js"></script>
<script type="text/javascript" src="/js/extjs/ux/tab-scroller-menu.js"></script>
<script type="text/javascript" src="/js/extjs/ux/Ext.ux.TinyMCE.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGridSorter.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGrid.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGridColumnResizer.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGridColumns.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGridLoader.js"></script>
<script type="text/javascript" src="/js/extjs/ux/treegrid/TreeGridNodeUI.js"></script>

<!-- DESKTOP CSS -->
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/desktop.css" />
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/icons-large.css" />
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/icons.css" />

<!-- CORE -->
<script type="text/javascript" src="/js/webtricks/namespaces.js"></script>
<script type="text/javascript" src="/js/webtricks/data/connection.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/application.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/module.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/about.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/desktop.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/tree.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/manager.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/fields/fieldcontainer.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/dialogs/dialog.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/dialogs/itembrowser.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/dialogs/upload.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/dialogs/showvalidationresult.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/market/packager.js"></script>

<script type="text/javascript" src="/js/webtricks/shell/applications/media/imageeditor.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/reports/logviewer.js"></script>

<script type="text/javascript" src="/js/webtricks/shell/applications/search/search.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/domainmanager.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/rolemanager.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/securitydetails.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/securityeditor.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/selectaccount.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/security/usermanager.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/tools/run.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/webedit/dialogs/lockeditems.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/workbox.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/contenttree.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/datetimefield.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/groupcombobox.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/notification.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/remotecomponent.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/shortcut.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/startmenu.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/taskbar.js"></script>

<script type="text/javascript" src="/js/webtricks/shell/controls/form/combotree.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/form/groupedcombobox.js"></script>

<script type="text/javascript" src="/js/awesomeuploader/Ext.ux.AwesomeUploader.js"></script>
<script type="text/javascript" src="/js/awesomeuploader/swfupload.js"></script>
<script type="text/javascript" src="/js/awesomeuploader/Ext.ux.XHRUpload.js"></script>


<!-- QoDesk -->
<!-- This dynamic file will load all the modules the member has access to and setup the desktop -->
<script src="/index.php/webtricks/desktop/application/"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16282548-2']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body></body>
</html>