<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="EXPIRES" content="-1">

<title>WebTricks CMS</title>

<!-- EXT JS LIBRARY -->
<!-- Using cachefly -->
<link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all.css" />
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base-debug.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>

<script type="text/javascript" src="/js/extjs/ux/miframe.js"></script>
<script type="text/javascript" src="/js/extjs/ux/ribbon.js"></script>
<script type="text/javascript" src="/js/extjs/ux/tab-scroller-menu.js"></script>

<!-- DESKTOP CSS -->
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/desktop.css" />
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/icons-large.css" />
<link rel="stylesheet" type="text/css" href="/media/shell/base/default/css/icons.css" />

<!-- CORE -->
<script type="text/javascript" src="/js/webtricks/namespaces.js"></script>
<script type="text/javascript" src="/js/webtricks/data/connection.js"></script>
<!-- <script type="text/javascript" src="/js/webtricks/shell/webedit.js"></script> -->
<script type="text/javascript" src="/js/webtricks/shell/module.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/about.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/desktop.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/dialogs/itembrowser.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/dialogs/upload.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/tree.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/contentmanager/manager.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/media/imageeditor.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/applications/tools/run.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/contenttree.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/notification.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/remotecomponent.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/shortcut.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/startmenu.js"></script>
<script type="text/javascript" src="/js/webtricks/shell/controls/taskbar.js"></script>

<script type="text/javascript" src="/js/awesomeuploader/Ext.ux.AwesomeUploader.js"></script>
<script type="text/javascript" src="/js/awesomeuploader/swfupload.js"></script>
<script type="text/javascript" src="/js/awesomeuploader/Ext.ux.XHRUpload.js"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16282548-2']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<script src="/index.php/webtricks/webedit/application/"></script>

</body>
</html>